using System;

namespace Robowire.RobOrm.Core.Migration
{
    public interface IMigrationScriptBuilder
    {
        void CreateTable(string tableName, string pkColumnName, Type pkColumnType, bool pkAutogenerated);

        void CreateColumn(
            string tableName,
            string columnName,
            string columnType,
            bool allowsNulls,
            bool unique);

        void CreateForeignKey(
            string referringTableName,
            string referringColumnName,
            string referredTableName,
            string referredColumnName);

        void AddCustomScript(string beforeMigration, string afterMigration);
    }
}
