using System;
using System.Text;

using Robowire.RobOrm.Core.Internal;
using Robowire.RobOrm.Core.Migration;

namespace Robowire.RobOrm.SqlServer.Migration
{
    public class SqlMigrationScriptBuilder : IMigrationScriptBuilder
    {
        private const string VERSION_TABLE_NAME = "Roborm_Schema_Version";
        private const string APPLY_DT_COLUMN_NAME = "ApplyDt";
        private const string SCHEMA_HASH_COLUMN_NAME = "SchemaHash";
        private const string SKIP_LABEL = "rbrm_afterscript";

        private readonly StringBuilder _tablesBuilder = new StringBuilder();
        private readonly StringBuilder _columnsBuilder = new StringBuilder();
        private readonly StringBuilder _keysBuilder = new StringBuilder();

        private string _beforeMigrationCustom;
        private string _afterMigrationCustom;
        
        public void CreateTable(string tableName, string pkColumnName, Type pkColumnType, bool pkAutogenerated)
        {
            var identity = string.Empty;
            var pkTypeName = SqlTypeMapper.GetSqlTypeName(pkColumnType, 0);

            if (pkAutogenerated)
            {
                identity = "IDENTITY(1,1) ";
            }

            _tablesBuilder.AppendLine($"IF NOT EXISTS(SELECT TOP 1 1 FROM sys.tables WHERE name = '{tableName}')");
            _tablesBuilder.AppendLine("BEGIN");
            _tablesBuilder.Append("\t");
            _tablesBuilder.AppendLine($"CREATE TABLE [{tableName}] ([{pkColumnName}] {pkTypeName} {identity}NOT NULL, ");
            _tablesBuilder.AppendLine(
                $"\tCONSTRAINT [PK_{tableName}] PRIMARY KEY CLUSTERED ([{pkColumnName}] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]");
            _tablesBuilder.AppendLine("\t);");
            _tablesBuilder.AppendLine("END");
            _tablesBuilder.AppendLine();
        }

        public void CreateColumn(string tableName, string columnName, string columnType, bool allowsNulls, bool unique)
        {
            _columnsBuilder.AppendLine(
                $"IF NOT EXISTS(SELECT TOP 1 1 FROM sys.tables t INNER JOIN sys.columns c ON t.object_id = c.object_id WHERE t.name = '{tableName}' AND c.name = '{columnName}')");
            _columnsBuilder.AppendLine("BEGIN");

            _columnsBuilder.AppendLine($"\tALTER TABLE [{tableName}] ADD [{columnName}] {columnType};");
            
            _columnsBuilder.AppendLine("END");

            _columnsBuilder.Append(
                $"ALTER TABLE [{tableName}] ALTER COLUMN [{columnName}] {columnType}");

            _columnsBuilder.Append(allowsNulls ? " NULL" : " NOT NULL").AppendLine(";").AppendLine();

            var uniConstraintName = $"UQ_{tableName}_{columnName}";

            if (!unique)
            {
                _columnsBuilder.Append($"IF OBJECT_ID('{uniConstraintName}') IS NOT NULL ")
                    .AppendLine($"ALTER TABLE [{tableName}] DROP CONSTRAINT [{uniConstraintName}];");
            }
            else
            {
                _columnsBuilder.Append($"IF OBJECT_ID('{uniConstraintName}') IS NULL ")
                    .AppendLine($"ALTER TABLE [{tableName}] ADD CONSTRAINT [{uniConstraintName}] UNIQUE NONCLUSTERED [{columnName}];");
            }

        }

        public void CreateForeignKey(
            string referringTableName,
            string referringColumnName,
            string referredTableName,
            string referredColumnName)
        {
            var constraintName = $"FK_{referringTableName}_{referringColumnName}__{referredTableName}_{referredColumnName}";

            _keysBuilder.AppendLine($"IF OBJECT_ID('{constraintName}') IS NULL ");

            _keysBuilder.Append(
                    $"\tALTER TABLE [{referringTableName}] ADD CONSTRAINT [{constraintName}] FOREIGN KEY ([{referringColumnName}])")
                .AppendLine($" REFERENCES [{referredTableName}] ([{referredColumnName}]);");

            _keysBuilder.AppendLine();
        }

        public void AddCustomScript(string beforeMigration, string afterMigration)
        {
            _beforeMigrationCustom = beforeMigration;
            _afterMigrationCustom = afterMigration;
        }

        private void RenderHead(StringBuilder sb, string schemeHash)
        {
            sb.AppendLine($"IF NOT EXISTS(SELECT TOP 1 1 FROM sys.tables WHERE name = '{VERSION_TABLE_NAME}')");
            sb.AppendLine($"\tCREATE TABLE {VERSION_TABLE_NAME} ({APPLY_DT_COLUMN_NAME} DATETIME NOT NULL, {SCHEMA_HASH_COLUMN_NAME} VARCHAR(256) NOT NULL);");
            sb.AppendLine();

            sb.AppendLine(
                $"IF ((SELECT TOP 1 {SCHEMA_HASH_COLUMN_NAME} FROM {VERSION_TABLE_NAME} ORDER BY {APPLY_DT_COLUMN_NAME} DESC) = '{schemeHash}') \r\n\t GOTO {SKIP_LABEL};");

            sb.AppendLine("BEGIN TRAN;");
            sb.AppendLine("BEGIN TRY");
            sb.AppendLine();
        }

        private void RenderFoot(StringBuilder sb, string schemeHash)
        {
            sb.AppendLine();

            sb.AppendLine(
                $"INSERT INTO {VERSION_TABLE_NAME} ({APPLY_DT_COLUMN_NAME}, {SCHEMA_HASH_COLUMN_NAME}) VALUES (GETDATE(), '{schemeHash}');");

            sb.AppendLine("\r\n\tCOMMIT;");

            sb.AppendLine("END TRY");
            sb.AppendLine("BEGIN CATCH");
            sb.AppendLine("\tROLLBACK;");
            sb.AppendLine("\tTHROW;");
            sb.AppendLine("END CATCH");

            sb.AppendLine($"{SKIP_LABEL}:");
        }

        public string ToString(string versionHash)
        {
            var sb = new StringBuilder();

            RenderHead(sb, versionHash);

            if (!string.IsNullOrWhiteSpace(_beforeMigrationCustom))
            {
                sb.AppendLine();
                sb.AppendLine(_beforeMigrationCustom);
                sb.AppendLine();
            }

            sb.Append(_tablesBuilder);
            sb.Append(_columnsBuilder);
            sb.Append(_keysBuilder);

            if (!string.IsNullOrWhiteSpace(_afterMigrationCustom))
            {
                sb.AppendLine();
                sb.AppendLine();
                sb.AppendLine(_afterMigrationCustom);
                sb.AppendLine();
            }

            RenderFoot(sb, versionHash);

            return sb.ToString();
        }
    }
}
