using System;
using System.Text;

using Robowire.RobOrm.Core.Internal;
using Robowire.RobOrm.Core.Migration;

namespace Robowire.RobOrm.SqlServer.Migration
{
    internal class StoredProcedureMigrationScriptBuilder : IMigrationScriptBuilder
    {
        private const string VERSION_TABLE_NAME = "Roborm_Schema_Version";
        private const string APPLY_DT_COLUMN_NAME = "ApplyDt";
        private const string SCHEMA_HASH_COLUMN_NAME = "SchemaHash";
        private const string SKIP_LABEL = "rbrm_afterscript";

        private readonly StringBuilder _tablesBuilder = new StringBuilder();
        private readonly StringBuilder _columnsBuilder = new StringBuilder();
        private readonly StringBuilder _keysBuilder = new StringBuilder();

        private string _beforeMigrationCustom;
        private string _afterMigrationCustom;

        public void CreateTable(string tableName, string pkColumnName, Type pkColumnType, bool pkAutogenerated)
        {
            var pkTypeName = SqlTypeMapper.GetSqlTypeName(pkColumnType, 0);

            _tablesBuilder.Append("EXEC dbo.robormsp_ensuretable ")
                .Append(SqlString(tableName)).Append(", ")
                .Append(SqlString(pkColumnName)).Append(", ")
                .Append(SqlString(pkTypeName)).Append(", ")
                .Append(pkAutogenerated ? "1" : "0")
                .AppendLine(";");
        }

        public void CreateColumn(string tableName, string columnName, string columnType, bool allowsNulls, bool unique)
        {
            _columnsBuilder.Append("EXEC dbo.robormsp_ensurecolumn ")
                .Append(SqlString(tableName)).Append(", ")
                .Append(SqlString(columnName)).Append(", ")
                .Append(SqlString(columnType)).Append(", ")
                .Append(allowsNulls ? "1" : "0").Append(", ")
                .Append(unique ? "1" : "0")
                .AppendLine(";");
        }

        public void CreateForeignKey(
            string referringTableName,
            string referringColumnName,
            string referredTableName,
            string referredColumnName)
        {
            _keysBuilder.Append("EXEC dbo.robormsp_createfk ")
                .Append(SqlString(referringTableName)).Append(", ")
                .Append(SqlString(referringColumnName)).Append(", ")
                .Append(SqlString(referredTableName)).Append(", ")
                .Append(SqlString(referredColumnName))
                .AppendLine(";");
        }

        public void AddCustomScript(string beforeMigration, string afterMigration)
        {
            _beforeMigrationCustom = beforeMigration;
            _afterMigrationCustom = afterMigration;
        }

        public string ToString(string versionHash)
        {
            var sb = new StringBuilder();

            RenderHead(sb, versionHash);

            if (!string.IsNullOrWhiteSpace(_beforeMigrationCustom))
            {
                sb.AppendLine();
                sb.AppendLine(_beforeMigrationCustom);
                sb.AppendLine();
            }

            sb.Append(_tablesBuilder);
            sb.Append(_columnsBuilder);
            sb.Append(_keysBuilder);

            if (!string.IsNullOrWhiteSpace(_afterMigrationCustom))
            {
                sb.AppendLine();
                sb.AppendLine();
                sb.AppendLine(_afterMigrationCustom);
                sb.AppendLine();
            }

            RenderFoot(sb, versionHash);

            return sb.ToString();
        }

        private static string SqlString(string value)
        {
            return "N'" + (value ?? string.Empty).Replace("'", "''") + "'";
        }

        private static void RenderHead(StringBuilder sb, string schemeHash)
        {
            sb.AppendLine($"IF NOT EXISTS(SELECT TOP 1 1 FROM sys.tables WHERE name = '{VERSION_TABLE_NAME}')");
            sb.AppendLine($"\tCREATE TABLE {VERSION_TABLE_NAME} ({APPLY_DT_COLUMN_NAME} DATETIME NOT NULL, {SCHEMA_HASH_COLUMN_NAME} VARCHAR(256) NOT NULL);");
            sb.AppendLine();

            sb.AppendLine(
                $"IF ((SELECT TOP 1 {SCHEMA_HASH_COLUMN_NAME} FROM {VERSION_TABLE_NAME} ORDER BY {APPLY_DT_COLUMN_NAME} DESC) = '{schemeHash}') \r\n\t GOTO {SKIP_LABEL};");

            sb.AppendLine("BEGIN TRAN;");
            sb.AppendLine("BEGIN TRY");
            sb.AppendLine();
        }

        private static void RenderFoot(StringBuilder sb, string schemeHash)
        {
            sb.AppendLine();

            sb.AppendLine(
                $"INSERT INTO {VERSION_TABLE_NAME} ({APPLY_DT_COLUMN_NAME}, {SCHEMA_HASH_COLUMN_NAME}) VALUES (GETDATE(), '{schemeHash}');");

            sb.AppendLine("\r\n\tCOMMIT;");

            sb.AppendLine("END TRY");
            sb.AppendLine("BEGIN CATCH");
            sb.AppendLine("\tROLLBACK;");
            sb.AppendLine("\tTHROW;");
            sb.AppendLine("END CATCH");

            sb.AppendLine($"{SKIP_LABEL}:");
        }
    }
}
