using System;
using System.Collections.Generic;

using Newtonsoft.Json;

namespace Robowire.RobOrm.Core.EntityModel
{
    public interface IEntity
    {
        [JsonIgnore]
        string DbEntityName { get; }

        [JsonIgnore]
        bool IsDirty { get; }

        [JsonIgnore]
        object PrimaryKeyValue { get; set; }

        [JsonIgnore]
        Type PrimaryKeyType { get; }

        [JsonIgnore]
        bool IsPrimaryKeyAutogenerated { get; }
        
        void ReadSelf(IDataRecord row);

        bool ReadPrimaryKey(IDataRecord reader);

        IEnumerable<Tuple<string, Type>> GetReferenceProperties();

        IEntitySet OpenProperty(string propertyName);

        SaveMethodType GetSaveMethodType();

        IEnumerable<EntityColumnValue> GetValues();
    }
}