using System;
using System.Collections.Generic;
using System.Reflection;

namespace Robowire.RobOrm.Core.Internal
{
    public static class PkHandlingHelper
    {
        private static readonly HashSet<Type> s_numericTypes = new HashSet<Type>
        {
            typeof(byte),
            typeof(sbyte),
            typeof(ushort),
            typeof(uint),
            typeof(ulong),
            typeof(short),
            typeof(int),
            typeof(long),
            typeof(decimal),
            typeof(double),
            typeof(float)
        };

        public static bool IsPkAutogenerated(PropertyInfo pkProperty)
        {
            if (!pkProperty.CanRead)
            {
                throw new InvalidOperationException($"PrimaryKey property {pkProperty} must have a getter");
            }

            var propertyType = Nullable.GetUnderlyingType(pkProperty.PropertyType) ?? pkProperty.PropertyType;

            if (!s_numericTypes.Contains(propertyType))
            {
                if (!pkProperty.CanWrite)
                {
                    throw new InvalidOperationException($"Primary Key property {pkProperty} must have a setter, because the type {pkProperty.PropertyType} cannot be used with IDENTITY");
                }

                return false;
            }

            return !pkProperty.CanWrite;
        }
    }
}
