using System;

namespace Robowire.RobOrm.Core.Migration.Internal
{
    public class ScriptBuilderProxy : IMigrationScriptBuilder
    {
        private readonly IMigrationScriptBuilder[] m_builders;

        public ScriptBuilderProxy(params IMigrationScriptBuilder[] builders)
        {
            m_builders = builders;
        }

        public void CreateTable(string tableName, string pkColumnName, Type pkColumnType, bool pkAutogenerated)
        {
            foreach (var b in m_builders)
            {
                b.CreateTable(tableName, pkColumnName, pkColumnType, pkAutogenerated);
            }
        }

        public void CreateColumn(string tableName, string columnName, string columnType, bool allowsNulls, bool unique)
        {
            foreach (var b in m_builders)
            {
                b.CreateColumn(tableName, columnName, columnType, allowsNulls, unique);
            }
        }

        public void CreateForeignKey(
            string referringTableName,
            string referringColumnName,
            string referredTableName,
            string referredColumnName)
        {
            foreach (var b in m_builders)
            {
                b.CreateForeignKey(referringTableName, referringColumnName, referredTableName, referredColumnName);
            }
        }

        public void AddCustomScript(string beforeMigration, string afterMigration)
        {
            foreach (var migrationScriptBuilder in m_builders)
            {
                migrationScriptBuilder.AddCustomScript(beforeMigration, afterMigration);
            }
        }
    }
}
