name: Build Portal

on:
  push:
    branches:
      - main  # Změňte na vaši hlavní větev, pokud není 'main'
  pull_request:
    branches:
      - main  # Změňte na vaši hlavní větev, pokud není 'main'
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Visual Studio Build Tools
      uses: microsoft/setup-msbuild@v1

    - name: Print Working Directory
      run: pwd

    - name: List Files in Working Directory
      run: dir

    - name: Restore NuGet packages
      run: nuget restore Elsa.Portal/Elsa.Portal.csproj -PackagesDirectory packages

    - name: Build
      run: msbuild Elsa.Portal/Elsa.Portal.csproj /p:Configuration=Release
