name: Build Portal

on:
  push:
    branches:
      - main  # Změňte na vaši hlavní větev, pokud není 'main'
  pull_request:
    branches:
      - main  # Změňte na vaši hlavní větev, pokud není 'main'
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Set up Visual Studio Build Tools
      uses: microsoft/setup-msbuild@v1

    - name: Restore NuGet packages
      run: nuget restore Elsa.Portal/Elsa.Portal.csproj -PackagesDirectory packages

    - name: Build with MSBuild
      run: |
        & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe" Elsa.Portal/Elsa.Portal.csproj /p:Configuration=Release

    - name: Print MSBuild Logs
      run: |
        echo "MSBuild Logs" > build_logs.txt
        type build_logs.txt
