name: Build Portal

on:
  push:
    branches:
      - main  # Ujistěte se, že máte větev 'main' nebo změňte na správnou větev
  pull_request:
    branches:
      - main  # Ujistěte se, že máte větev 'main' nebo změňte na správnou větev
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Visual Studio Build Tools
      uses: microsoft/setup-msbuild@v1

    - name: Print Working Directory
      run: echo %cd%

    - name: List Files in Working Directory
      run: dir

    - name: Clear NuGet Cache
      run: nuget locals all -clear

    - name: Restore NuGet packages
      run: nuget restore Elsa.Portal/Elsa.Portal.csproj -PackagesDirectory packages

    - name: List NuGet Packages
      run: dir /s /b | findstr /i ".nupkg"

    - name: Create Diagnostic Logs
      run: |
        echo "System Information" > diagnostics.txt
        systeminfo >> diagnostics.txt
        echo "Environment Variables" >> diagnostics.txt
        set >> diagnostics.txt
        echo "Directory Listing" >> diagnostics.txt
        dir >> diagnostics.txt
        echo "NuGet Configurations" >> diagnostics.txt
        nuget config -list >> diagnostics.txt
        echo "Installed Packages" >> diagnostics.txt
        nuget list >> diagnostics.txt

    - name: Build
      run: msbuild Elsa.Portal/Elsa.Portal.csproj /p:Configuration=Release /v:diag
