name: Build Portal

on:
  push:
    branches:
      - main  # Změňte na vaši hlavní větev, pokud není 'main'
  pull_request:
    branches:
      - main  # Změňte na vaši hlavní větev, pokud není 'main'
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Restore NuGet packages
      run: nuget restore Elsa.sln -PackagesDirectory packages

    - name: Build with MSBuild
      run: |
        # Locate MSBuild.exe path using environment variables
        $msbuildPath = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe"
        if (-Not (Test-Path $msbuildPath)) {
          Write-Host "MSBuild.exe not found at path: $msbuildPath"
          exit 1
        }
        & $msbuildPath Elsa.sln /p:Configuration=Release

    - name: Print MSBuild Logs
      run: |
        echo "MSBuild Logs" > build_logs.txt
        type build_logs.txt
