name: Build Portal

on:
  push:
    branches:
      - main  # Změňte na vaši hlavní větev, pokud není 'main'
  pull_request:
    branches:
      - main  # Změňte na vaši hlavní větev, pokud není 'main'
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Visual Studio Build Tools
      uses: microsoft/setup-msbuild@v1

    - name: Clear NuGet Cache
      run: nuget locals all -clear

    - name: Restore NuGet packages
      run: nuget restore Elsa.Portal/Elsa.Portal.csproj -PackagesDirectory packages

    - name: Install Newtonsoft.Json Package
      run: nuget install Newtonsoft.Json -Version 13.0.1 -OutputDirectory packages

    - name: List Installed NuGet Packages
      run: dir packages /s /b

    - name: Build
      run: msbuild Elsa.Portal/Elsa.Portal.csproj /p:Configuration=Release /v:diag

    - name: Print MSBuild Logs
      run: type build_logs.txt
