name: Build Portal

on:
  push:
    branches:
      - main  # Změňte na vaši hlavní větev, pokud není 'main'
  pull_request:
    branches:
      - main  # Změňte na vaši hlavní větev, pokud není 'main'
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install PowerShell
      run: |
        sudo apt-get update
        sudo apt-get install -y powershell

    - name: Install .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '4.x'  # Adjust according to your project's .NET version

    - name: Clear NuGet Cache
      run: dotnet nuget locals all --clear

    - name: Restore NuGet packages
      run: dotnet restore Elsa.Portal/Elsa.Portal.csproj

    - name: List NuGet Packages
      run: find . -name "*.nupkg"

    - name: Create Diagnostic Logs
      run: |
        echo "System Information" > diagnostics.txt
        uname -a >> diagnostics.txt
        echo "Environment Variables" >> diagnostics.txt
        printenv >> diagnostics.txt
        echo "Directory Listing" >> diagnostics.txt
        ls -la >> diagnostics.txt
        echo "NuGet Configurations" >> diagnostics.txt
        dotnet nuget list source >> diagnostics.txt
        echo "Installed Packages" >> diagnostics.txt
        dotnet list package >> diagnostics.txt

    - name: Pre-build Action - Run PowerShell Script
      run: pwsh path/to/your/script.ps1  # Adjust the path to your script

    - name: Build
      run: dotnet build Elsa.Portal/Elsa.Portal.csproj -c Release

    - name: Print Build Logs
      run: cat build_logs.txt
