name: Build Portal

on:
  push:
    branches:
      - main  # Změňte na vaši hlavní větev, pokud není 'main'
  pull_request:
    branches:
      - main  # Změňte na vaši hlavní větev, pokud není 'main'
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Visual Studio Build Tools
      uses: microsoft/setup-msbuild@v1

    - name: Install NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Print Working Directory
      run: echo ${PWD}

    - name: List Files in Working Directory
      run: Get-ChildItem

    - name: Clear NuGet Cache
      run: nuget locals all -clear

    - name: Restore NuGet packages
      run: nuget restore Elsa.Portal/Elsa.Portal.csproj -PackagesDirectory packages

    - name: List NuGet Packages
      run: Get-ChildItem -Path packages -Recurse -Filter *.nupkg

    - name: Create Diagnostic Logs
      run: |
        echo "System Information" > diagnostics.txt
        systeminfo >> diagnostics.txt
        echo "Environment Variables" >> diagnostics.txt
        Get-ChildItem Env: | Out-File -Append -FilePath diagnostics.txt
        echo "Directory Listing" >> diagnostics.txt
        Get-ChildItem | Out-File -Append -FilePath diagnostics.txt
        echo "NuGet Configurations" >> diagnostics.txt
        nuget config -list >> diagnostics.txt
        echo "Installed Packages" >> diagnostics.txt
        nuget list >> diagnostics.txt

    - name: Pre-build Action - Run PowerShell Script
      run: powershell -File path/to/your/script.ps1  # Adjust the path to your script

    - name: Build
      run: msbuild Elsa.Portal/Elsa.Portal.csproj /p:Configuration=Release

    - name: Print MSBuild Logs
      run: |
        echo "MSBuild Logs" >> build_logs.txt
        type build_logs.txt
