name: Build Portal

on:
  push:
    branches:
      - main  # Ujistěte se, že máte větev 'main' nebo změňte na správnou větev
  pull_request:
    branches:
      - main  # Ujistěte se, že máte větev 'main' nebo změňte na správnou větev
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Visual Studio Build Tools
      uses: microsoft/setup-msbuild@v1

    - name: Print Working Directory
      run: Write-Output $PWD

    - name: List Files in Working Directory
      run: Get-ChildItem -Recurse

    - name: Clear NuGet Cache
      run: nuget locals all -clear

    - name: Restore NuGet packages
      run: nuget restore Elsa.Portal/Elsa.Portal.csproj -PackagesDirectory packages

    - name: List NuGet Packages
      run: Get-ChildItem -Recurse | Where-Object { $_.Name -match "\.nupkg$" }

    - name: Build
      run: msbuild Elsa.Portal/Elsa.Portal.csproj /p:Configuration=Release /v:diag

    - name: Print MSBuild Logs
      run: Get-Content build_logs.txt
